name: PR Check

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install Dependencies
        run: yarn install

      - name: Verify Code
        run: yarn validate

      - name: Build Project
        run: yarn build

      - name: Build Docker image
        run: docker build -t barellano/docker-react .